<?php
$value = array (
  'wwwprefix' => 'http://127.0.0.1/jinjintuanweb',
  'imgprefix' => 'http://127.0.0.1/jinjintuanweb',
  'cssprefix' => 'http://127.0.0.1/jinjintuanweb',
  'sitename' => '团购网',
  'sitetitle' => '团购网',
  'abbreviation' => '团购网',
  'couponname' => '优惠券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'indexteam' => '12',
  'sideteam' => '4',
  'editor' => 'kind',
  'description' => '购网，专业的技术及运营团队。7*24小时在线客服为商家、客户提供方便服务。',
  'keywords' => '团购网',
  'invitecredit' => '1',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => 'http://127.0.0.1/wap',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'givemoney' => '0.1',
  'task_i_hour' => '0',
  'task_i_min' => '20',
  'task_i_sec' => '0',
  'task_i_num' => '1',
);
?>