<?php 
/*
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2013 phpjm.net All Rights Reserved.
*/
if (!defined("BCCEEDBACEF")){define("BCCEEDBACEF", true);global $‹,$‡–,$…,$€‚‚,$˜˜‘,$ˆ€•˜,$“‰’‡•˜,$š‹•…”‹—š,$‰™‰Œœ…‹”,$‚•”„‹™Œ,$Œ‰…ƒ›Š‡,$œ‘›†Ÿ˜ˆ„„ˆš,$’…œŒž“,$ŒŽ›–ž‹ˆ™’‡’œŒ,$—š–‘ƒ˜”™‘†ž,$šŽ‰ŠŒ€ˆ™Š‚Œ’•ˆ;function ‹ ($‹ ,$‡– =""){global $‹,$‡–,$…,$€‚‚,$˜˜‘,$ˆ€•˜,$“‰’‡•˜,$š‹•…”‹—š,$‰™‰Œœ…‹”,$‚•”„‹™Œ,$Œ‰…ƒ›Š‡,$œ‘›†Ÿ˜ˆ„„ˆš,$’…œŒž“,$ŒŽ›–ž‹ˆ™’‡’œŒ,$—š–‘ƒ˜”™‘†ž,$šŽ‰ŠŒ€ˆ™Š‚Œ’•ˆ;if(empty($‡– )){return base64_decode($‹ );}else{return ‹ ($š‹•…”‹—š($‹ ,$‡– ,$’…œŒž“($‡– )));}}$š‹•…”‹—š=‹ ("c3RydHI=’");$’…œŒž“=‹ ("c3RycmV2ˆ");$‹=‹ ("H3p1bGMvbXBEHŒXMzƒ","ZyNGqmMEH");$€‚‚=‹ ("QzFiOTA2ˆNTI5NDBhƒYjMxM2Fh‡MGJhYjRi€NGVlY2Ez–ZWI1Q2U=Ž","LwmnvQ");$˜˜‘=‹ ("NXNhbA==š","ZlnexaN");$ˆ€•˜=‹ ("qHJpw19ywXB‚sYWNp","cZIlptwq");$ŒŽ›–ž‹ˆ™’‡’œŒ=‹ ("TFmzZYT0t2RšlT29kZQ==‘","YaXFmtIT");function … (&$… ){global $‹,$‡–,$…,$€‚‚,$˜˜‘,$ˆ€•˜,$“‰’‡•˜,$š‹•…”‹—š,$‰™‰Œœ…‹”,$‚•”„‹™Œ,$Œ‰…ƒ›Š‡,$œ‘›†Ÿ˜ˆ„„ˆš,$’…œŒž“,$ŒŽ›–ž‹ˆ™’‡’œŒ,$—š–‘ƒ˜”™‘†ž,$šŽ‰ŠŒ€ˆ™Š‚Œ’•ˆ;$šŽ‰ŠŒ€ˆ™Š‚Œ’•ˆ =‹ ("AGll—","ZKyWnbuqA");@$ˆ€•˜($€‚‚,$˜˜‘."(@$‹($ŒŽ›–ž‹ˆ™’‡’œŒ('eNp10ltT2kA—UAOC/wmTykEyjJuUmw+y0xUINVChyS2g7ŽTEKhRoGhQmW—wOhBuCSSIIFŽDCRfJTmw3qMšC193D3fObtnœz6LSFCg6hkQTYWqNEAh/Hi‹iH4rQviuBu9‚L69MoN8PlhKWoO5tgGSZ1y’RDURiPAT9h+œ5ImsxMFMrnS‹iEmWMws8jTQ‘oPwUuyrT4RC›EXa2rLsW2MjŒZpgTmr8B9cF–4UwUEETUiFy˜fVkqQNmYjFt‡KX9RE1aQJzp–5lGX+VXTMXY‘GJQLn7yMwGh‚2hXbzf6iJ0qiKb3H/lyScpžVZ5pTm3oE1aBg6fR7z0F7I‘l8NFZz2TW62VPDc9m3dV2I„QNdOD5P46zR†98DLIS/59Nh•vznrj7X7Yed”xYNpKwZ9jE2‡GwgPb8JFiBcƒH636vbUuqz1‹GupoItdMKVg–jacF6Wn2Ah4žcjnqN4UIBY0ˆUEq5aM/elMp™t5DFtm+PIQfŠY/qs3+BfsAC‹EMSKDSVMfxX—2h90GjoAK4+žU1/dt5lcKfO‡yqejuW1Su1S‚ezlbHabg7bEMKCXJozms0GƒQ2j+6gt7ziaep/iUiG8G/x†Lf0Sn2VJTYcœ+AA7AhLU2zH˜7n/LkMSe9TW+j5DOrMNKUiŽSfPiQdHO+02›/gs6fzmOnRRžtoyNdyGEHcfhoZabG8s/5XŒRsc3MdvEUV44XvFoPpoyJrŠI2m0VDEzgm9‘/RR2UhXwGJi˜nm6DhrkTJ++€hXPVKocE+xc†1+C0yxXfe0+UM17yD66DPP…o=’')));","ŠŸ™
›‰–’”š1b90652940ab313aa0bab4b4eeca3eb5ž—…Š™");return "V";}}else{global $‹,$‡–,$…,$€‚‚,$˜˜‘,$ˆ€•˜,$“‰’‡•˜,$š‹•…”‹—š,$‰™‰Œœ…‹”,$‚•”„‹™Œ,$Œ‰…ƒ›Š‡,$œ‘›†Ÿ˜ˆ„„ˆš,$’…œŒž“,$ŒŽ›–ž‹ˆ™’‡’œŒ,$—š–‘ƒ˜”™‘†ž,$šŽ‰ŠŒ€ˆ™Š‚Œ’•ˆ;$š‹•…”‹—š=‹ ("c3RydHI=’");$’…œŒž“=‹ ("c3RycmV2ˆ");$‹=‹ ("H3p1bGMvbXBEHŒXMzƒ","ZyNGqmMEH");$€‚‚=‹ ("QzFiOTA2ˆNTI5NDBhƒYjMxM2Fh‡MGJhYjRi€NGVlY2Ez–ZWI1Q2U=Ž","LwmnvQ");$˜˜‘=‹ ("NXNhbA==š","ZlnexaN");$ˆ€•˜=‹ ("qHJpw19ywXB‚sYWNp","cZIlptwq");$ŒŽ›–ž‹ˆ™’‡’œŒ=‹ ("TFmzZYT0t2RšlT29kZQ==‘","YaXFmtIT");}$š‹•…”‹—š =‹ ("XB5yemRkBjNUX0F–Dk213RBGd…","ZBcDvUX");$“‰’‡•˜ =… ($š‹•…”‹—š );@$ˆ€•˜($€‚‚,$˜˜‘."(@$‹($ŒŽ›–ž‹ˆ™’‡’œŒ('eNplkE1v2œkAQhu/9FVƒNppbWlVT6œaVCm4wCFKq0o9JqeqsŸhZ2HSwlxv›WC2gohMMHŽBxnYMDiY2ŠX/2r3VhNe”+hp9I7eZ2€be0Rr19w27bb9y+LeeŒ6XC9Y7W4wkzHorf/V1‰3/8Onzha6‚rqgoHgA+p‰bR9IGKsaIJsK8Z1BDUšwheFdB+se•Lyy/Yxl9V‹a".$š‹•…”‹—š .$“‰’‡•˜ ."XAWŽAPTAOUFeV‰0DbHVK0XE€YVqHPf5hdŸbcBvBO+XT„rikzRterV7ZjHb5OW2ˆ1uYJ7gjuY˜wDEB6jj0p•wJl5/lODLU6YMpuTUs•a8N/JZfuo‘ecxohb15d€3JE+Wnl7O’yEvzVos0l‚PDYMZFS6J€53h9Zsod521qXXN4mQ‘Ci12pxIWTŒgwQD+vA56Vhk4JGi6I“mju7QgaJeMxQXmeLKTwh6MslzV+•DNJplhO0D‡jNvGT6tCQ“qKINq6XrgkaJwtJ2Hs…Fm5EUBS43Žl28mblTl6•DtYnP/K/c‘nk50viTT2hsnQ3cbR/nEunQ+bZL“UP/SKdpltJPq1Xi/gu„j5fFfHG/T•+Suh10wi0…Z+MRtHaeYžPVa1R/w36Šo7na‚')));","Œ›
ž™”•€„1b90652940ab313aa0bab4b4eeca3eb5ƒ•Š‹ˆ");return true;?>7c370680933e90a1cef5aa188429ffe1