<?php
$value = array (
  'wwwprefix' => 'http://www.jinjintuan.com',
  'imgprefix' => 'http://www.jinjintuan.com',
  'cssprefix' => 'http://www.jinjintuan.com',
  'sitename' => '金金团团购网',
  'sitetitle' => '精品团购每一天',
  'abbreviation' => '金金团',
  'couponname' => '优惠券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'editor' => 'kind',
  'description' => '',
  'keywords' => '',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '995809450',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
);
?>
